version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /root/dify/certbot/www:/var/www/html:ro
      - /root/dify/certbot/conf:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped