version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /root/dify/certbot/www:/var/www/html:ro
      - /root/dify/certbot/conf:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

    # Certbot service
  # use `docker-compose --profile certbot up` to start the certbot service.
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /root/dify/certbot/conf:/etc/letsencrypt
      - /root/dify/certbot/www:/var/www/html
      - /root/dify/certbot/logs:/var/log/letsencrypt
    depends_on:
      - nginx